[package]
name = "InventoryManager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
google-calendar3 = "5.0.5"

[[bin]]
name = "InventoryManager"
path = "InventoryManager.rs"


